version: "3.8"
services:
  unsubscriber:
    container_name: 'unsubscriber'
    build:
      context: './'
    volumes:
      - "./:/app"
    depends_on:
      - rabbit
      - pgsql
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbit'
    logging:
      driver: none
    ports:
      - "5672:5672"
      - "15672:15672"
  pgsql:
    image: postgres:9.6
    container_name: 'pgsql'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres